remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

#theme: jekyll-theme-midnight
